### ISSUE TITLE
Autotuner

### ISSUE THREAD

**Issue by We-Sing** [marktilles/kiln-controller-v4#1]
Hi, maybe a simpel question/answer... 
I try to run de Autotuner, but it does not work orI do something wrong: 

_pi@raspberrypi:~/kiln-controller $ python kiln-tuner.py recordprofile zn.csv
Could not import config file.
Copy config.py.EXAMPLE to config.py and adapt it for your setup.

Thanks for your help!

**Comment by We-Sing** [comment]
Sorry, to quick...found it : https://github.com/jbruce12000/kiln-controller/issues/182

**Comment by marktilles** [comment]
You know, I’ve never used it … sorry
